### ISSUE TITLE
Please add JSS in the future

### ISSUE THREAD

**Issue by Peretz30** [trendmicro-frontend/react-dropdown#12]
Plain CSS sucks! So I recoment to you [JSS](https://github.com/cssinjs/jss) to use it in the future updates.

**Comment by roth1002** [comment]
It is the just dropdown library implement by react.

Even the  CSS sucks. We cannot promise that JSS never be sucks some years in the future.

**Comment by cheton** [comment]
Close this issue as it does not give constructive feedback and it will introduce breaking change at least. We will do the enhancement when we have a clear roadmap to make component updates.
