### ISSUE TITLE
How to style arrow in submenu

### ISSUE THREAD

**Issue by Peretz30** [trendmicro-frontend/react-dropdown#16]
Hello! Tell me please, how can I style arrow in dropdown menu item with submenu?
![image](https://user-images.githubusercontent.com/27721091/40039960-125a3500-5821-11e8-9286-cb20ca96dfb0.png)

**Comment by shanehandley** [comment]
Note that you can use a nested selector to achieve this with styled components:
```javascript
const Toggle = styled(Dropdown.Toggle)`
	span:last-of-type {
		border-top-color: white;
	}
`;
```
