### ISSUE TITLE
Trouble with dropdown CSS

### ISSUE THREAD

**Issue by sudeeptarlekar** [trendmicro-frontend/react-dropdown#20]
Hi,

I installed and added drop-down with the guidelines told in the Readme, but while rendering dropdown CSS is not getting applied correctly. I checked Webpack logs and found out that only `react-dropdown.css` is getting compiled. Not able to figure out why CSS is not getting applied.

Can someone here help me out?

Thanks in advance

SS of react-dropdown
![react-dropdown](https://user-images.githubusercontent.com/23317691/49284933-15b4ce80-f4bc-11e8-8089-4c0b8a3665c5.png)

SS of webpack
![screenshot from 2018-11-30 16-22-22](https://user-images.githubusercontent.com/23317691/49284986-3d0b9b80-f4bc-11e8-88a0-d0e288d4ce9f.png)

**Comment by roth1002** [comment]
@sudeeptarlekar 

Did you directly import react-dropdown.css ?

I used this dropdown as below:

```
import '@trendmicro/react-dropdown/dist/react-dropdown.css';
import Dropdown from '@trendmicro/react-dropdown';

export default Dropdown;
export {
    DropdownToggle,
    DropdownMenu,
    DropdownSubMenu,
    MenuItem,
    DropdownButton
} from '@trendmicro/react-dropdown';
```

and import this everywhere if you want to use it.

**Comment by roth1002** [comment]
I closed this issue. 
If need to reopen, do it
