### ISSUE TITLE
Dropdown onClose not firing when press DropdownToggle

### ISSUE THREAD

**Issue by adarrra** [trendmicro-frontend/react-dropdown#21]
Hi, I want to add animation for closing DropdownMenu. 
I think to add some style within onClose callback. Nevertheless it can be closed by pressing DropdownToggle,  this callback are not called. It called only when click is outside dropdown

**Comment by roth1002** [comment]
We need not animation here

If you wanted use this

might change CSS by use styled component for work around as below:

```
const StyledDropdownMenu = styled(DropdownMenu)`
   &.dropdown---Wq_VE.open---2SG_5 > .dropdown-menu---2R-2v {
       visibility: visible;
       opacity: 1;
       transition: opacity .2s linear;
   }

   &.dropdown-menu---2R-2v {
       visibility: hidden;
        opacity: 0;
        transition: visibility 0s .2s, opacity .2s linear;
   }
`;
```
