### ISSUE TITLE
Is there an example of the search filter that is functional

### ISSUE THREAD

**Issue by mandelllee** [trendmicro-frontend/react-dropdown#28]
The current example for the search filter doesn't seem to filter at all and I don't see any callbacks to make it work. Is there a version of the example with this.

**Comment by roth1002** [comment]
The UI component does not provide filter on data, I suggest you can filter on you options self
since the filter maybe implement on reducer/API/xstate/any other state management in your App

Ex: use withPropsOnchange in recompose to do this.
