### ISSUE TITLE
Add more styling properties or document it

### ISSUE THREAD

**Issue by anikolaev** [trendmicro-frontend/react-dropdown#3]
I wanted to style menu items to change hover background color, font, paddings. I use styled components so I just added typical code:

```js
const StyledMenuItem = styled(MenuItem)`
  &:hover {
    background: ${styleConstants.selectionColor};
  }
  padding: 0 6px;
`
```

In component's render() function:

```jsx
<StyledMenuItem onClick={onDownloadCSV}>Download CSV</StyledMenuItem>
```

That didn't work as styled were applied to \<li\> element and I need to style <a> element inside \<li\>. I've added 'a' tag:
```js
const StyledMenuItem = styled(MenuItem)`
  a {
    &:hover {
      background: ${styleConstants.selectionColor};
    }
    padding: 0 6px;
  }
`
```
It still didn't work. I had to append '!important;' to each rule due to higher specificity of css styles. I could fix it with the following code:

```js
const StyledMenuItem = styled(MenuItem)`
  && {
    a {
      &:hover {
        background: ${styleConstants.selectionColor};
      }
      padding: 0 6px;
    }
  }
`
```
But I thing it should be reflected in the documentation or some ability to style menu items should be implemented.

**Comment by cheton** [comment]
For pseudo-classes, you may have to use as many `&` as you need, or use the `!important` rule:
```js
styled.div`
  & { ... } /* .foo {} */
  && { ... } /* .foo.foo {} */
  &&& { ... } /* .foo.foo.foo {} */
`
```

Otherwise, you can use inline styles for custom styling with a stateless function component.

**Comment by cheton** [comment]
Updated documentation
https://github.com/trendmicro-frontend/react-dropdown/blob/master/README.md#custom-styling
