### ISSUE TITLE
Need Help on React-Dropdown

### ISSUE THREAD

**Issue by kamaldlk** [trendmicro-frontend/react-dropdown#7]
Thanks for awesome lib. Im using React-Dropdown On the table I want to display drop-down in inside the table column name. when I click the icon it's showing menu inside the column only.   I'm not able to see full menu need to append in Body please help me on this 
![screen shot 2018-02-02 at 1 16 19 pm](https://user-images.githubusercontent.com/9652523/35722195-554a706a-081b-11e8-886c-a757069b150b.png)

outside table its showing correctly 
![screen shot 2018-02-02 at 1 16 33 pm](https://user-images.githubusercontent.com/9652523/35722211-6785dc24-081b-11e8-938d-bd334926934e.png)

**Comment by cheton** [comment]
Your table container contains the "overflow: hidden" proprty so that dropdown menu it getting clipped. You have to fix this problem on the your table component.

**Comment by kamaldlk** [comment]
Thanks for Response If I remove overflow hidden getting dropdown. but the table rows and columns collapsed. There is any alternate solution @cheton  :(

**Comment by cheton** [comment]
You may have to allow custom styling for dropdown only, not applying the rule to the whole table.

**Comment by cheton** [comment]
A hack for modifying the style of its parent node:
```jsx
<Dropdown
    ref={node => {
        if (node) {
            const dropdownElement = ReactDOM.findDOMNode(node);
            dropdownElement.parentNode.style.overflow = 'initial';
        }
    }}
>
    :   :   :
</Dropdown>
```

**Comment by kamaldlk** [comment]
Thank you so much @cheton  :) This Hack working Fine.
